name: Test & Deploy
on: 
  push:
    branches:
      - cicd
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yay! This works"
  runUnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: install the dependencies
        run: npm i
      - name: run unit tests
        run: npm test utils

